### ISSUE TITLE
Cannot load some modules

### ISSUE THREAD

**Issue by PasaOpasen** [Koziev/rulemma#3]
```python
import rutokenizer
#Traceback (most recent call last):
#
#  File "<ipython-input-34-fe9c2c9403a4>", line 1, in <module>
#    import rutokenizer

#ModuleNotFoundError: No module named 'rutokenizer'


import rupostagger
#Traceback (most recent call last):
#
 # File "<ipython-input-35-f3c22b8e9cc6>", line 1, in <module>
#    import rupostagger

#ModuleNotFoundError: No module named 'rupostagger'


import rulemma

lemmatizer = rulemma.Lemmatizer()

lemmatizer.load()

tokenizer = rutokenizer.Tokenizer()
#Traceback (most recent call last):
#
#  File "<ipython-input-39-e44cc92630e8>", line 1, in <module>
#    tokenizer = rutokenizer.Tokenizer()
#
#NameError: name 'rutokenizer' is not defined
```

Я могу сделать просто лемматизацию через lemmatizer, не выводя части речи?

**Comment by Koziev** [comment]
>Я могу сделать просто лемматизацию через lemmatizer, не выводя части речи?

Нет, этот лемматизатор работает поверх тэггера. Я его сделал для проекта чатбота и там всегда нужна морфологическая информация. Поэтому для его использования нужно установить еще небольшую кучку модулей:

1) https://github.com/Koziev/rusyllab
2) https://github.com/Koziev/rutokenizer
3) https://github.com/Koziev/ruword2tags (важно - там есть проблема установки словарной базы из git lfs, в README есть по этому поводу описание)
4) https://github.com/Koziev/rupostagger

Если не хочется возится с этим, попробуйте яндексовский pymystem3 или UDPipe.
