### ISSUE TITLE
Would you be open to porting this to Javascript?

### ISSUE THREAD

**Issue by giorgosera** [Koziev/rulemma#4]
Hey @Koziev,

I stumbled upon your project here while searching for Russian lemmatizer implementations in JS. 

Would you be open to porting this to Javascript? I can start working on this but I wanted to check with you first.

Let me know what you think! Great work on this project by the way 💯

**Comment by Koziev** [comment]
Hi,
>Would you be open to porting this to Javascript? 
It would be very difficult, I suppose. The lemmatizer requires two other tools - [part-of-speech tagger](https://github.com/Koziev/rupostagger) and [dictionary](https://github.com/Koziev/ruword2tags) - to be ported. And POS tagger is built upon CRFSuite package.
Last but not least - I'm not a JS developer, I can't write or support it :(

**Comment by giorgosera** [comment]
Hey Ilya,

Thanks for the reply. I was actually proposing to do it myself but I thought I'd first get your opinion  👍 

Yes, indeed since the lemmatizer has some dependencies the task might be harder than I expected. 

Thanks anyways! :)

**Comment by Koziev** [comment]
By the way, loot at [https://github.com/koorchik/node-mystem3](https://github.com/koorchik/node-mystem3), for example. It is a kind of wrapper for MyStem pos tagger and lemmatizer.

**Comment by giorgosera** [comment]
That works indeed. Nice finding! Thank you :)
